### ISSUE TITLE
Нет прав на открытие .docx файла

### ISSUE THREAD

**Issue by undetected-capybara** [Cmi1o/website-scrinner#1]
Сканирование фотографий прошло штатно, фотографии добавились в соответствующую папку. Выскочила ошибка при открытии .docx файла. Вероятно, ошибка связана с тем, что файл уже существовал.

Traceback (most recent call last):
  File "D:\projects\website-screener\src\main.py", line 85, in <module>
    main()
  File "D:\projects\website-screener\src\main.py", line 78, in main
    files_manager.create_new_docx()
  File "D:\projects\website-screener\src\files_interactions.py", line 53, in create_new_docx
    doc.save(path)
  File "D:\projects\website-screener\.venv\Lib\site-packages\docx\document.py", line 149, in save
    self._part.save(path_or_stream)
  File "D:\projects\website-screener\.venv\Lib\site-packages\docx\parts\document.py", line 108, in save
    self.package.save(path_or_stream)
  File "D:\projects\website-screener\.venv\Lib\site-packages\docx\opc\package.py", line 167, in save
    PackageWriter.write(pkg_file, self.rels, self.parts)
  File "D:\projects\website-screener\.venv\Lib\site-packages\docx\opc\pkgwriter.py", line 34, in write
    phys_writer = PhysPkgWriter(pkg_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\website-screener\.venv\Lib\site-packages\docx\opc\phys_pkg.py", line 109, in __init__
    self._zipf = ZipFile(pkg_file, "w", compression=ZIP_DEFLATED)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\zipfile\__init__.py", line 1320, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'D:\\projects\\website-screener\\src\\assets\\1158424.docx'

Process finished with exit code 1

**Comment by undetected-capybara** [comment]
Если файл предварительно удалить, то всё работает.
